### ISSUE TITLE
No such file or directory ../bin/python

### ISSUE THREAD

**Issue by MathiasSchrooten** [dickermoshe/zappadock#4]
Hello! First of all, thanks for this repo, it's a really helpful tool!

I had just set up my docker image through ZappaDock and was able to install all packages & have my flask app run as well.
Now, when I tried running the zappa deploy command I received the following error:

```

`/var/task/zappa-venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/cli.py", line 3422, in handle
    sys.exit(cli.handle())
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/cli.py", line 630, in dispatch_command
    self.deploy(self.vargs["zip"], self.vargs["docker_image_uri"])
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/cli.py", line 852, in deploy
    self.create_package()
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/cli.py", line 2775, in create_package
    self.zip_path = self.zappa.create_lambda_zip(
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/core.py", line 635, in create_lambda_zip
    copytree(
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/utilities.py", line 69, in copytree
    copy_file(src, dst, item)
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/utilities.py", line 50, in copy_file
    copytree(s, d, metadata, symlinks, ignore)
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/utilities.py", line 69, in copytree
    copy_file(src, dst, item)
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/utilities.py", line 50, in copy_file
    copytree(s, d, metadata, symlinks, ignore)
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/utilities.py", line 69, in copytree
    copy_file(src, dst, item)
  File "/var/task/zappa-venv/lib/python3.9/site-packages/zappa/utilities.py", line 52, in copy_file
    shutil.copy2(s, d) if metadata else shutil.copy(s, d)
  File "/var/lang/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/var/lang/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/task/venv/bin/python'
```

Do you have any idea what this could have caused?

Thank you so much!

**Comment by dickermoshe** [comment]
@MathiasSchrooten
I'm suspecting you're running on Windows.
What virtual environment is activated within Zappadock ? `venv` or `zappa-venv` ?
Are you running the deploy command from within Zappadock ?

**Comment by migohomeservices** [comment]
I am also getting the same issue while running zappa deploy when venv is activated. 
And also, could not run zappa deploy inside zappa-venv.
I am using macos

**Comment by dickermoshe** [comment]
Fixed in newest version

**Comment by dannyeei** [comment]
I'm still getting this error. I see there's a symlink from python to python3.9
